export const GENRE = {
  ROCK: "Rock",
  ELECTRONIC: "Electronic",
  SOUL_AND_RNB: "Soul & RnB",
  HIP_HOP: "Hip Hop",
  LOUNGE: "Lounge",
  LOFI_AND_CHILL_BEATS: "Lofi & Chill Beats",
  JAZZ: "Jazz",
  CINEMATIC: "Cinematic",
  HOLIDAY: "Holiday",
  RETRO: "Retro",
  WORSHIP: "Worship",
  FUNK: "Funk",
  POP: "Pop",
  CLASSICAL: "Classical",
  CORPORATE: "Corporate",
};
